### ISSUE TITLE
Error: Unable to read beyond the end of the stream.

### ISSUE THREAD

**Issue by Uikri** [MaikelChan/AFSPacker#1]
Hi. I don't know how else to contact someone about issues, so here I am. I am trying to use AFSPacker to extract the contents of ADX_USA.AFS from my Dragon Ball Z Budokai 3 disc. I have copied ADX_USA.AFS off of the disc and onto my external HDD, in the same directory as AFSPacker. The directory is K:\0000-UTILS\AFSPacker-v1.2.2\. I opened a command prompt window in the same directory as AFSPacker. I typed in **AFSPacker -e ADX_USA.AFS K:\0-ADX\DBZ [list_file]**. I got the following:

        #----------------------------------------------------------------#
        #                   AFS Packer - Version 1.2.2                   #
        #      By PacoChan - https://github.com/MaikelChan/AFSPacker     #
        #----------------------------------------------------------------#

Extracting files...

Reading TOC... 4540/4540

Error: Unable to read beyond the end of the stream.

Am I doing something wrong? Could you please advise me on how to solve this? I get the feeling I don't fully understand what I'm doing, as I'm not terribly experienced with command prompt. I apologize if this isn't the appropriate place to post this. I don't really know much about github, either.

![AFSPacker Error](https://user-images.githubusercontent.com/3394107/94952881-47c65b80-04ac-11eb-8f21-c709e7d4bf4e.png)

**Comment by MaikelChan** [comment]
Hello!

Sorry you are having that issue. First, could you try removing the `[list_file]` part of the command? That's to optionally specify a name of a text file that will contain a list of the names of the files and their order (it's necessary for some games). So the command would look like this: `AFSPacker -e ADX_USA.AFS K:\0-ADX\DBZ`

However, I suspect that that's not the issue. There are many variants of the AFS format, and it could be that AFSPacker is not compatible with the ones of that game. Would you be able to host that file somewhere for me to test it?

Thanks!

**Comment by Uikri** [comment]
> 
> 
> Hello!
> 
> Sorry you are having that issue. First, could you try removing the `[list_file]` part of the command? That's to optionally specify a name of a text file that will contain a list of the names of the files and their order (it's necessary for some games). So the command would look like this: `AFSPacker -e ADX_USA.AFS K:\0-ADX\DBZ`
> 
> However, I suspect that that's not the issue. There are many variants of the AFS format, and it could be that AFSPacker is not compatible with the ones of that game. Would you be able to host that file somewhere for me to test it?
> 
> Thanks!

Omg I'm so sorry for not replying sooner. I have some memory issues due to a neurological disorder and I don't use my PC very often but I'm still sorry. I've uploaded the file to mediafire, and you can find it [here](http://www.mediafire.com/file/ezhzq7zulkzkimg/ADX_USA.AFS/file). I hope it's still okay to ask for your help with this matter.

**Comment by MaikelChan** [comment]
Hi again! You don't need to worry at all.

I checked the file, and it turns out that it already works fine in the latest version of the program I released a couple weeks ago. I fixed an issue in other files that happens to also fix your issue. So please test it again with the latest version 1.2.3. I hope that works fine for you.

Have a nice day!
