### ISSUE TITLE
[REPORT] - Urban Reign PS2

### ISSUE THREAD

**Issue by ghost** [MaikelChan/AFSPacker#13]
Congratulations on the tool, man! Tools like this helps too much to work automatically! Well, I used it in a PlayStation 2 game entitled Urban Reign (USA, EUR), but, I had a problem: the game gave black screen and does not start at all. If in the future you can take a look at a possible increment to support this game, I would be grateful! Thank you very much and see you.

**Comment by MaikelChan** [comment]
Hi! Thanks, glad it is useful.

Can you give more details? What file did you edit in that game, and could you provide the original one and your edited one for me to see what broke in the new one?

Thanks again.

**Comment by ghost** [comment]
Sorry for the delay in replying. Thank you for your attention. Well, to be more detailed, I'm using the DVD000.AFS of the game Urban Reign (USA) of Ps2... I use the unpacker normally, and the repacker... with the new AFS generated and rebuilt in iso, the game does not enter, gives black screen. Here below I will provide the files, both the original and the modified.

[Download](https://www.mediafire.com/file/f616cjjjqn33wwb/AFS+Samples.7z/file)

**Comment by MaikelChan** [comment]
Sorry for the delay. I've been investigating the issue, but it will take me a while for a fix, as it basically requires rewriting a bunch of stuff. It's another one of those games that decides to do AFS files with its own unique twist. I'll let you know when I have progress on this.

**Comment by MaikelChan** [comment]
Actually, I found a much easier way of fixing it (hopefully). Could you try this version and see if it works for you?

[AFSPacker.zip](https://github.com/MaikelChan/AFSPacker/files/12567018/AFSPacker.zip)

**Comment by ghost** [comment]
Hello! Of course, I'll test it here and later, as soon as possible, I'll give you feedback. Thanks in advance.

**Comment by ghost** [comment]
It worked perfectly, man! Thank you very much for your attention. Your tool will be of great help for my future project.

**Comment by MaikelChan** [comment]
Glad to hear it!
