### ISSUE TITLE
File check

### ISSUE THREAD

**Issue by MarkSpizu** [MaikelChan/AFSPacker#14]
Can you check this file? I can't unpack it

https://download.gg/en/file-15866476_20f2f9405123a51e

**Comment by MaikelChan** [comment]
Hi, I just checked that file. Despite the .afs extension, that's not an AFS file. It's completely unrelated, so my program won't be able to extract it.

**Comment by MarkSpizu** [comment]
Thanks for the info. Now it's clear why it didn't work.
