### ISSUE TITLE
It says stream doesn't seem to contain valid AFS data.

### ISSUE THREAD

**Issue by GameDevBhavesh** [MaikelChan/AFSPacker#20]
bhavesh@GameDevBhaveshMint:~/Downloads/ps2/working/Urban Reign (USA)$ $HOME/Downloads/ps2/afs/AFSPacker -e DVD000.AFS  TEST

        #----------------------------------------------------------------#
        #                   AFS Packer - Version 2.1.2                   #
        #             https://github.com/MaikelChan/AFSPacker            #
        #                                                                #
        #                Powered by AFSLib - Version 2.0.3               #
        #              https://github.com/MaikelChan/AFSLib              #
        #                                                                #
        #                    By MaikelChan / PacoChan                    #
        #----------------------------------------------------------------#

[2:11:34am] [Error] Stream doesn't seem to contain valid AFS data.

**Comment by GameDevBhavesh** [comment]
Solved just extracted it again from iso file did the work : )

**Comment by MaikelChan** [comment]
I'm glad you managed to fix the issue :)
