### ISSUE TITLE
Could not find a part of the path 

### ISSUE THREAD

**Issue by marmwar** [MaikelChan/AFSPacker#3]
Hi, there, first off just wanted to say thanks for your tool, doesnt seem to be much else out there trying to extract ATF files. 
So I was trying to extract an AFS archive and got hit with a 'could not find a part of the path <afspacker then lists a path here that doesnt even exist>' error.  

![image](https://user-images.githubusercontent.com/47910111/98436458-7b973100-20a9-11eb-9e70-f3e591110dd5.png)

This is an issue with all the AFS archives I extracted from a game.  It seems that there is an issue where they expect other files and file directories to exist, but they arent there. That " \gra\ " folder it lists in the screenshot does not exist in " E:\users\ * \desktop\ " folder at all, infact it does not exist period.

**Comment by MaikelChan** [comment]
Hi, thanks for the report.

I released a new version of the program recently, version 1.2.3. Could you try if it works? And if not, would you be able to upload the file somewhere for me to test it?

Thanks!

**Comment by smb123w64gb** [comment]
Got similar result in Soul Calibur 2 for GC,PS2,XBOX
![image](https://user-images.githubusercontent.com/4001226/101994932-18d22000-3c7b-11eb-9357-1e5c0a358c72.png)

**Comment by MaikelChan** [comment]
Hi! Would you be able to upload the AFS file for me to test?

Thanks!

**Comment by smb123w64gb** [comment]
This is the ps2 Movie afs. https://drive.google.com/file/d/1EzBGqHravRCLSs-W4VrnVCiUQ_Prv44R/view?usp=sharing

**Comment by MaikelChan** [comment]
Hello, I uploaded an updated version (1.2.4) that fixes the issue. Turns out that Soul Calibur 2 doesn't store file metadata correctly, and instead of storing file names, it stores truncated paths. That made the program to try to extract the files into non-existing folders. I made a workaround to ignore those paths in case there are.

Hope this works for you!
