### ISSUE TITLE
The program doesn't start

### ISSUE THREAD

**Issue by ghost** [MaikelChan/AFSPacker#4]
When I click on it, it instantly closes, and I don't know why, I have NET framework over 5.0, and I am on Windows.

**Comment by MaikelChan** [comment]
Hello, sorry for the late answer.

You need to run the program from a command prompt to enter the commands you need. If you are not familiar using the command prompt, you can try this:
- Create a text file in the same folder where the program is, and call it "AFSPacker.bat" (or any name but with .bat extension).
- Edit it with notepad or other text editor and write a command there. You have the instructions of how to use the program in the Readme.
- For example, if you want to extract the files of an AFS file called "Data.AFS" to a folder called "Extracted_Data", write: `AFSPacker -e "Data.AFS" "Extracted_Data"`
- Save the AFSPacker.bat file.
- Double click on it. This should run the command and extract the files.

Hope that helps.

Greetings!

**Comment by ghost** [comment]
Thanks a lot for the response, I solved the problem by simply opening the cmd, and I typed in the file name to open it, and it works.
