### ISSUE TITLE
How do you even run this?

### ISSUE THREAD

**Issue by EphyMusic** [MaikelChan/AFSPacker#5]
This is more of a Pebkac issue, honestly. I've gone into folder where everything was extracted and tried running the commands in CMD and Powershell, and neither one allowed me to use the program. I'm not sure how to "install" this if it needs to be installed. I'm just trying to get some samples of Heather Mason's voice for my new track, yo'...

**Comment by MaikelChan** [comment]
Hello, sorry for the late answer.

What do you mean by "neither one allowed me to use the program"? Does any error appear or something? You don't need to install the program or anything. Just run it from a command prompt with the parameters you want. There are instructions in the readme.

Greetings.
