### ISSUE TITLE
Year, Month, and Day parameters describe an un-representable DateTime.

### ISSUE THREAD

**Issue by hyunlee11037** [MaikelChan/AFSPacker#6]
Steps to reproduce:
1. Run on PowerShell:
`.\AFSPacker.exe -i movie.afs`
Get the result on console:
`[12:00:00 PM] [Error] Year, Month, and Day parameters describe an un-representable DateTime.`

I'm using Windows 10, with  .NET Core Runtime 3.1 installed. It might be possible that the movie.afs has corrupted datetime values, but I'm still able to extract the video files from the archive by other means.

**Comment by MaikelChan** [comment]
Hi!

What version of AFSPacker are you using? And could you send your movie.afs for testing? In theory, these cases in which date info is not correct should be handled correctly, but I guess there are still some edge cases.

**Comment by hyunlee11037** [comment]
I'm using version 2.1.0. And here's movie.afs, but it's a big file, around
850 MB.

https://drive.google.com/file/d/1ZdV8aOss8vnXdJ43z6U5m5oHA2pVfZ6w/view?usp=sharing

**Comment by MaikelChan** [comment]
This was already fixed on 1.x versions of the program but it looks that I forgot to add the fix back in 2.x. I've published a new version that fixes the issue: https://github.com/MaikelChan/AFSPacker/releases/tag/v2.1.1

Hope it now works fine!

**Comment by AdrianeYves** [comment]
Ive got the same issues with all commands even with version 2.1.1

heres the image
https://i.postimg.cc/HsktXT3b/image-2022-04-18-095444483.png

I am trying to open valkyria chronicles 3's psp voice afs by sega but it seems that it doesnt work for me.

I am using Windows 10 and my netcore version is 5.0.403.. i also installed the said required version of net core which is 3.1
https://i.postimg.cc/d0nsGGJ9/image-2022-04-18-184041098.png

**Comment by MaikelChan** [comment]
Hi!

Can you share a sample AFS file?

**Comment by AdrianeYves** [comment]
I am trying to extract this file:

https://www.mediafire.com/file/t8bmwt9an7b6vai/OD_VOICE.zip/file
ive got this from the vc3 psp game file itself.

**Comment by MaikelChan** [comment]
I tested the file with the latest version (2.1.1) and it's working fine for me. Looking at your screenshots, it seems you are still using 2.1.0. Can you make sure you are using the latest version?

**Comment by AdrianeYves** [comment]
OH SH*T yah my bad XD, anyways thanks for this awesome tool

**Comment by MaikelChan** [comment]
Glad it works! :)
