### ISSUE TITLE
Could not find .JSON file

### ISSUE THREAD

**Issue by brockdev7** [MaikelChan/AFSPacker#8]
First off, just wanted to say thank you for your work on this project. There isn't many options when it comes to working with AFS archives from what I've seen so this is great! Just need some guidance as I didn't see anything in the wiki regarding needing a .json file. Is this something that should be in the AFS archive, because there aren't any .json files in my circumstance.

![image](https://user-images.githubusercontent.com/103797240/163656956-467d7220-7dd0-4829-a649-63466f71a2c2.png)

Thanks again!

**Comment by brockdev7** [comment]
Sorry, I didn't realize I had to extract using your tool first. Makes sense, I'm a dummy! Thanks again!

**Comment by MaikelChan** [comment]
Hi. Glad you figured it out!

Extracting generates de .json, which only contains certain info in order to, when recreating an afs file, it maintains the same format (there are many variants) and the same file order.
