### ISSUE TITLE
Can't use hard to understand

### ISSUE THREAD

**Issue by FoxerMoxer** [MaikelChan/AFSPacker#9]
I wanted to use this so I did "cd [AFSPACKERFILELOCATION]" and then did "AFSPacker -e <[FILELOCATION]\DATA0.AFS> <Desktop>
yet it still doesn't work there is no more info online and I've been trying this for the past 2 hours with no result I have the  3.1 .Net Framework installed yet it still doesn't work.

**Comment by MaikelChan** [comment]
Did you figure out the issue. Did it show any error?
